version: '3.8'

services:
    postgres:
        image: postgres:16
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:7
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    mongodb:
        image: mongo:7
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    postgres_data:
    redis_data:
    mongo_data:
